POST http://localhost:3000/signup
Content-Type: application/json

{
    "name": "hassan",
    "email": "h@gmail.com",
    "password": "12345678",
    "phone": "969687123",
    "gender": "male",
    "age": 27
}

###

POST  http://localhost:3000/
Content-Type: application/json

{
    "id": 465465
}

###

POST http://192.168.43.170:8081/login
Content-Type: application/json
 
{
    "email": "h@gmail.com",
    "password": "12345678"
}

###

GET http://192.168.43.170:8081/categories

###

GET http://192.168.43.170:8081/appointments/634998d45c77ad1b570d3ebe

###

POST http://192.168.43.170:8081/appointments
Content-Type: application/json

{
    "patientId": "6349a957ecb5d7e10bbe1bdd",
    "doctorId": "",
    "category": { 
        "id": "6349d89d5c77ad1b570d3ebf", 
        "name": "Internal medicine" 
    },

    "timeslot": {
        "num": 4,
        "str": "11-12"
    }
}

###

POST http://192.168.43.170:8081/new-category
Content-Type: application/json

{
    "name": "Derma",
    "doctor": {
        "name": "Ahmed",
        "phone": "+223165465965"
    }
}

###

GET http://192.168.43.170:8081/doctors
